### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by romgrk** [sindrets/diffview.nvim#1]
Hi,

Is there a way to configure keybindings without using the setup function? Eg `nmap j DiffViewSelectNextEntry`?
It would be nice if the mappings were public so I can remap them freely. Ideally having the diffview panel have its own filetype is the best because one can then use the native ftplugin/after mechanism to set custom options & keybindings for that filetype.

Thanks

**Comment by sindrets** [comment]
Yes, I intended for the file panel to have its own filetype, it must have slipped my mind, so that will be fixed! 
I think I could have been clearer about it in the documentation, but the callback used in the configuration is really just a convenience. It's just a `string.format` under the hood and it produces something like: 

```
:lua require'diffview'.on_keypress('select_next_entry')<CR> 
```

The key binding tables' keys and values are just the `lhs` and `rhs` of `nvim_buf_set_keymap`. So you can set any custom normal mode mappings you want. Like:

```lua
-- ...
file_panel = {
  -- other maps...
  ["<leader>c"] = ":MyCustomMap",
}
```

**Comment by sindrets** [comment]
> Yes, I intended for the file panel to have its own filetype, it must have slipped my mind

Never mind, it does have its own filetype: `DiffviewFiles`. You should be able to use the `BufWinEnter` autocommand I think.

**Comment by romgrk** [comment]
Ok thanks :)
