### ISSUE TITLE
[Error] Cannot run DiffviewOpen and DiffviewFileHistory

### ISSUE THREAD

**Issue by smallpondtom** [sindrets/diffview.nvim#106]
Hi, I just installed this plugin and was about the try it out. But I get these error messages whenever I try to run `DiffviewOpen` and `DiffviewFileHistory`.

```
E5108: Error executing lua ...er/start/diffview.nvim/lua/diffview/views/file_entry.lua:425: Failed to set buffer 82
stack traceback:
        [C]: in function 'nvim_win_set_buf'
        ...er/start/diffview.nvim/lua/diffview/views/file_entry.lua:425: in function 'load_null_buffer'
        ...fview.nvim/lua/diffview/views/standard/standard_view.lua:46: in function 'init_layout'
        ...k/packer/start/diffview.nvim/lua/diffview/views/view.lua:46: in function 'open'
        ...im/site/pack/packer/start/diffview.nvim/lua/diffview.lua:60: in function 'file_history'
        [string ":lua"]:1: in main chunk
```

or

```
E5108: Error executing lua ...fview.nvim/lua/diffview/views/standard/standard_view.lua:47: Vim(lcd):E344: Can't find directory "diffview:" in cdpath
stack traceback:
        [C]: in function 'cmd'
        ...fview.nvim/lua/diffview/views/standard/standard_view.lua:47: in function 'init_layout'
        ...k/packer/start/diffview.nvim/lua/diffview/views/view.lua:46: in function 'open'
        ...im/site/pack/packer/start/diffview.nvim/lua/diffview.lua:53: in function 'open'
        [string ":lua"]:1: in main chunk
```

also I get this error message when I try to close an empty tab with `DiffviewClose` that comes out once I use `DiffviewOpen`

```
E5108: Error executing lua ...m/lua/diffview/views/file_history/file_history_panel.lua:119: attempt to index field 'render_data' (a nil value)
stack traceback:
        ...m/lua/diffview/views/file_history/file_history_panel.lua:119: in function 'destroy'
        ...fview.nvim/lua/diffview/views/standard/standard_view.lua:32: in function 'close'
        ...im/lua/diffview/views/file_history/file_history_view.lua:67: in function 'close'
        ...im/site/pack/packer/start/diffview.nvim/lua/diffview.lua:74: in function 'close'
        [string ":lua"]:1: in main chunk
```

These errors do not produce any logs. I just started using it and only have the default configurations. Any possible reasons?

My nvim version is v0.6.1 and :checkhealth did not raise any notable issues.

**Comment by sindrets** [comment]
This seems to be related to your setup.

```
E5108: Error executing lua ...fview.nvim/lua/diffview/views/standard/standard_view.lua:47: Vim(lcd):E344: Can't find directory "diffview:" in cdpath
```

This error is related to an `lcd` call, which is something I never call from this plugin. Maybe you have an auto-rooter or something? Or just some autocmds.

`DiffviewClose` fails because the views are never initialized properly due to the errors.

Please try to reproduce this issue with a minimal config. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

**Comment by smallpondtom** [comment]
@sindrets 

I found out the issue. I had the following code to resolve an issue I had with nvim-tree that it won't open up at my current working directory from start-up. After removing this I have no issues with `Diffview`.

```
vim.cmd([[
     augroup goToCurrentDirectory
     autocmd!
     autocmd VimEnter,WinEnter,BufEnter * lcd %:p:h
     augroup end
]])
```

**Comment by sindrets** [comment]
@smallpondtom It hinders Diffview because your autocmd doesn't make any checks to ensure that the path you are trying to `cd` to actually exists. When the plugin opens a buffer named something like `diffview:///null` - which is a valid buffer name - your code tries to `cd` to `diffview:`, which is not a real path. It shouldn't be a plugin's responsibility to do error handling for user autocmds. You should use `:h isdirectory()` or something similar to ensure the path exists. Something like:

```vim
au VimEnter,WinEnter,BufEnter * if isdirectory(expand("%:p:h")) | lcd %:p:h | endif
```

**Comment by smallpondtom** [comment]
@sindrets Thank you for the explanation and solution. I actually just edited the `autocmd` as 
```
au VimEnter * lcd %:p:h
```
and solved all my issues. But I will incorporate the error handling that you suggested.
