### ISSUE TITLE
Reference to jit crashes on neovim without luajit

### ISSUE THREAD

**Issue by benallan** [sindrets/diffview.nvim#116]
In lua/diffview/path.lua, there's a reference to jit which will crash on a neovim which wasn't compiled with luaJIT:

```
Error detected while processing /home/ben/.local/share/nvim/site/pack/packer/start/diffview.nvim/plugin/diffview.vim:
line    3:
E5108: Error executing lua ...ack/packer/start/diffview.nvim/lua/diffview/path.lua:6: attempt to index global 'jit' (a nil value)
```

Here's the line, and it seems to be the only reference to jit in the code:
```lua
local is_windows = jit.os == "Windows"
```

If it's only used to detect whether running on windows, maybe we could change it to something more compatible, e.g.:
```lua
local is_windows = vim.loop.os_uname().sysname == "Windows_NT"
```

**Comment by benallan** [comment]
Actually, I'm not sure whether it's incorrect to assume that jit is available in neovim.

[This comment](https://github.com/neovim/neovim/issues/14228#issuecomment-808740548) from jamessan was the first source I checked:
> Don't do that without checking whether jit is non-nil first. There's no requirement that nvim is built against LuaJIT.

But [this one from bfredl](https://github.com/neovim/neovim/issues/9760#issuecomment-800048366) suggests plugins can depend on it:
> >     Which part of luajit does neovim depend on otherwise?
> 
> The "jit" part. Core doesn't need it, but plugins are free to assume jit performance for an acceptable user experience.

**Comment by sindrets** [comment]
Are you compiling neovim without luajit? If so, I hope that's only because you're on a system that doesn't support luajit, because it's in many cases orders of magnitude faster than non-jit lua, and I think many lua plugins are designed with this performance in mind.

In any case, it wouldn't be difficult to work around this.

> `local is_windows = vim.loop.os_uname().sysname == "Windows_NT"`

`vim.loop.os_uname().sysname` has different values for MSVC and MINGW, so this is not a good approach. But I see that nvim-lspconfig uses this:

https://github.com/neovim/nvim-lspconfig/blob/50c821e2bf2182f4577168ee3bf959010582e177/lua/lspconfig/util.lua#L98

**Comment by benallan** [comment]
I'd actually prefer to use luajit (I realise it's much faster), but installing from snap on Ubuntu arm gave me non-jit lua, and trying again from the ppa had the same result.
```
NVIM v0.7.0-dev
Build type: RelWithDebInfo
Lua 5.1
```

I've now realised that a lot of plugins are broken without jit, so maybe it's better that I just figure out how to get neovim with luajit on Ubuntu arm.

**Comment by sindrets** [comment]
Luajit does support ARM architecture so you can definitely compile it yourself. Building nvim from source is pretty straight forward and doesn't take that long:

https://github.com/neovim/neovim/wiki/Building-Neovim

Regardless, since I only had this one reference to the `jit` global I opted to just use a workaround for now.

**Comment by benallan** [comment]
Thanks a lot!

When I found that both the ppa and the snap weren't built against luajit I assumed there must be a good reason, but you're right that luajit is available so I'll give compiling a go.

And the reason I initially went for the snap and ppa before compiling was that it was slightly easier to use with ansible, but compiling should work too.
