### ISSUE TITLE
Disable indentation guides in diffview

### ISSUE THREAD

**Issue by Tummetott** [sindrets/diffview.nvim#134]
Hello, 

I'm using [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) to show indentation guides. I diffview however, I want to disable them. It is possible via `require("indent_blankline.commands").disable()`. I tried using the `diff_buf_win_enter` (also tried `diff_buff_read`) hook but it's not working:

```lua
require'diffview'.setup({
    hooks = {
       diff_buf_win_enter = function()
            require("indent_blankline.commands").disable()
       end,
    }
})
```

The command is executed but indentation guides are still shown. When I run the command manually via `:lua require("indent_blankline.commands").disable()` after opening a diff view, it works. 
See: lukas-reineke/indent-blankline.nvim/issues/413

Can you explain whats going wrong there?
Thanks

**Comment by sindrets** [comment]
From a quick look at the indent-blankline source I can see that this is happening due to scheduling. They are responding to the `BufWinEnter` event before diffview's hooks are executed, and determine that the buffers should have indentation guides. They then schedule the part of the work that renders the guides. In the meantime, before the scheduled work is executed, diffview's hooks are called, and you try to disable the indent guides. However, as the work is already scheduled, it executes anyway after our hooks are done. To be clear, indent-blankline isn't doing anything wrong here. I suppose they could circumvent this by scheduling the work that clears the namespace upon disabling it.

You can get around this by just scheduling the work in the hook as well, such that it executes after indent-blankline has finished the first render:

```lua
diff_buf_read = function(bufnr)
  --- Normal local local options go here...

  vim.schedule(function()
    vim.api.nvim_buf_call(bufnr, function()
      require("indent_blankline.commands").disable()
    end)
  end)
end,
```
