### ISSUE TITLE
Diff incorrect when using git worktrees

### ISSUE THREAD

**Issue by dlvhdr** [sindrets/diffview.nvim#135]
When using git worktrees, the left hand side is the master branch instead of the HEAD of the current worktree.
I believe you're just not taking into account the HEAD of the current worktree.
Not sure how to debug this...

**Comment by sindrets** [comment]
I can't reproduce this.

> the left hand side is the master branch instead of the HEAD of the current
> worktree.

If you opened diffview without specifying a git rev, the left side should be the
index, not the head. I.e. the state of the file that you get when you run:

```sh
git show :path/to/file
# (Note the colon before the path)
```

> I believe you're just not taking into account the HEAD of the current
> worktree.

Whenever the plugin needs the HEAD rev, it gets it from git by running:

```sh
git rev-parse --revs-only HEAD
```

I'm just guessing here: maybe you have changed your `$GIT_WORK_TREE`, and / or
`$GIT_DIR` environment variables? Or any other variables that changes git's
behavior? The plugin is intentionally using your environment when running git
commands such that you can change these variables if you want to.

**Comment by sindrets** [comment]
@dlvhdr out of curiosity I checked your dotfiles, [and I found the culprit](https://github.com/dlvhdr/dotfiles/blob/bb80dbd6724bf51344f093ffb9866d7afb2ccfeb/.config/nvim/lua/dlvhdr/diffview.lua#L39). This means that every time you run:

```
:DiffviewOpen {...args}
```

It'll be expanded to:

```
:DiffviewOpen master {...args}
```

**Comment by dlvhdr** [comment]
Whoops my bad! Thanks for the help, this fixes it!

A bit unrelated, but I was facing the issue you helped me just solve bacause I'm working on a "check out" branch functionality for [gh-dash](www.github.com/dlvhdr/gh-dash).
I was wondering if there's a way to automatically get the base branch for a PR...?
I want to add a command that runs `DiffviewOpen {{current_branch}}..{{current_branch_base}}`, where `current_branch_base` is the branch that the PR is based of in GitHub.

**Comment by sindrets** [comment]
@dlvhdr I'm a bit confused about what you're asking. Git has no concept of a PR,
or a "merge request". These are concepts implemented by VCS repo hosting sites
like github and gitlab etc. So if you need to find out what branch a PR i
merging into, you need to find that out through github's API.

If you are asking how to get the range of revs since branch B forked from branch
A; then that is something git knows and can provide:

```
git diff A...B
```

The symmetric difference notation (triple dot) will diff the head of branch B
with the "merge-base" of A (the common ancestor of A and B). In other words, all
changes on B since it forked from A.

Do note however, if you're gonna use triple dot ranges in your code: `git-diff`
and `git-log` have almost opposite interpretations of what this notation means.
And `git-rev-parse` uses the `git-log` definition. This tripped me up when I
first was implementing this in diffview. Essentially:

```sh
git diff A...B
# means:
git diff $(git merge-base A B) B
```

```sh
git log A...B
# means:
git log A B --not $(git merge-base --all A B)
```

**Comment by dlvhdr** [comment]
Actually, this is perfect.
`DiffviewOpen master...{{my_branch}}` gives exactly what I want
Thanks!
