### ISSUE TITLE
Scrolling sometimes buggy

### ISSUE THREAD

**Issue by Shatur95** [sindrets/diffview.nvim#17]
Hi! Thank you a lot for the awesome plugin!

But I have some issues with scrolling. Sometimes one of the parts does not move and sometimes it moves, but the position is incorrect. It happens only if I use mouse wheel for scrolling:

[![asciicast](https://asciinema.org/a/H4Rqbz5r5NH1MixGtkYqLQwMO.svg)](https://asciinema.org/a/H4Rqbz5r5NH1MixGtkYqLQwMO)

**Comment by sindrets** [comment]
Glad you like it!

I'm not doing anything special to accomplish the scroll binding. I'm just using vim's internal `:h scroll-binding`. What you're seeing is just how scroll binding works in vim: window scrolling is not synchronized unless the window you are scrolling is focused. Thus, when you use the mouse to scroll a window that is not focused, scrolling is not synced. 

So if you use the mouse to scroll a lot, it's just a matter of getting used to clicking the buffer before you scroll, so that focus is brought to its window.

**Comment by Shatur95** [comment]
Oh, got it, thanks!

**Comment by CoreyCole** [comment]
got this working for me to scroll lock without clicking 
```lua
-- Auto-focus window on mouse scroll to make scrollbind work properly in diffview
vim.api.nvim_create_autocmd("WinScrolled", {
  callback = function()
    local current_buf_name = vim.api.nvim_buf_get_name(0)
    local current_win = vim.api.nvim_get_current_win()
    local mouse_win = vim.fn.getmousepos().winid
    
    -- Check if we're in a diffview context (either current window is diffview:// or has diff mode)
    local in_diff_context = current_buf_name:match("^diffview://") or vim.api.nvim_win_get_option(current_win, "diff")
    
    if in_diff_context then
      if mouse_win > 0 and vim.api.nvim_win_is_valid(mouse_win) then
        local mouse_buf = vim.api.nvim_win_get_buf(mouse_win)
        local mouse_buf_name = vim.api.nvim_buf_get_name(mouse_buf)
        
        -- Check if mouse is over a diff window (either diffview:// URL or a regular file in diff mode)
        -- Exclude the file panel
        if not mouse_buf_name:match("/panels/") then
          -- Check if it's a diffview buffer or if the window has diff mode enabled
          local is_diff_window = mouse_buf_name:match("^diffview://") or vim.api.nvim_win_get_option(mouse_win, "diff")
          
          if is_diff_window then
            vim.api.nvim_set_current_win(mouse_win)
          end
        end
      end
    end
  end,
})

```
