### ISSUE TITLE
I cannot run DiffViewOpen.

### ISSUE THREAD

**Issue by ElcomJ** [sindrets/diffview.nvim#170]
![diffview](https://user-images.githubusercontent.com/37147897/177388376-b76f187f-d74a-4438-a05b-cca6fd1c7eb5.png)

I recently found this wonderful extension and would like to use it in my neovim, but whenever I run the command 'DiffViewOpen' I get this error in the image above, I wonder if there is a way to solve it.

Thanks in advance.

**Comment by sindrets** [comment]
@ElcomJ From my very limited understanding of Portuguese, it seems like Plenary is unable to create the log file? Would have been useful if you had provided the error message in plain text.

Does your system user have write access to that path that you censored? What happens if you create that path? (`[...]/.cache/nvim/diffview.log`)

**Comment by ElcomJ** [comment]
![Captura de tela de 2022-07-05 17-19-17](https://user-images.githubusercontent.com/37147897/177409407-648760ff-295a-4763-be69-f998a9dcda00.png)

If possible, I would like to ask a question about the background color of added, changed and deleted lines.

I wonder if there is a way to change the background color of the image above to a color of my liking?

**Comment by sindrets** [comment]
Yes, adjust theses highlight groups: `DiffAdd`, `DiffDelete`, `DiffChange`, `DiffText`.

See `:h :highlight` for how to adjust highlight groups.
