### ISSUE TITLE
GitGutter symbols for Diffview and DiffHistory

### ISSUE THREAD

**Issue by ElcomJ** [sindrets/diffview.nvim#171]
Good morning, first of all congratulations for the great plugin :)

I wonder if I could put the GitGutter signs in place of the signcolumn in the DiffView and DiffHistory, as I think it would look better visually than just that gray gutter.

1 - Image of how it is at the moment
![Captura de tela de 2022-07-06 12-44-14](https://user-images.githubusercontent.com/37147897/177591260-c159576c-c12f-48b0-afe3-d9669c93f488.png)
.

2 - 2 - Image of how I would like to leave it.
![Captura de tela de 2022-07-06 12-43-54](https://user-images.githubusercontent.com/37147897/177591358-c07b048b-d0a2-47b8-ad2f-1d7771548dc5.png)

Thank you in advance :)

**Comment by sindrets** [comment]
@ElcomJ I don't really like this idea because it would communicate redundant information (the same information already communicated by the diff highlighting). If your problem really is that you don't like the gray highlighting (which is going to be different for different color schemes), you should just change the highlighting for the fold column. The highlight group is called `FoldColumn`. Either that, or disable the fold column all together (see `:h 'foldcolumn'`).
