### ISSUE TITLE
Buffer name is internally modified

### ISSUE THREAD

**Issue by asmodeus812** [sindrets/diffview.nvim#173]
Hi, i am having an issue with diffview modifying the name of the buffers when opening the view. Which causes certain language serves (which rely on being able to resolve the root directory) to fail to work. For example one such example is jdtls. 

Normal fully qualified buffer name
`/home/user/project/src/main/java/com/package/name/file.java`

However in diffview the buffer has a very different name 
`diffview:///home/user/project/.git/:0:/src/main/java/com/package/name` (note even the fname is missing at the end)

This introduces some issues where there is no reliable way to find the root directory consistently. Usually i am passing the full path directory to server config for example something like that. The sample below is using lspconfig's default server interface/api callback to resolve the root for a given language server. (the method .root_dir(full-path-to-file) requires a valid fs path)

```
local config = server.document_config.default_config
return config.root_dir(vim.fn.expand('%:p:h'))
```

**Comment by sindrets** [comment]
@asmodeus812 Buffer names of buffers that are not created by the plugin are never modified. I think you're confusing something here. The plugin needs to create buffers to represent the state of a file in different git revisions. The example you used (`diffview:///home/user/project/.git/:0:/src/main/java/com/package/name/file.java`) has the rev `:0:`. That's a stage number. Stage number 0 represents the state of the file with the currently staged changes. Note that this file does not actually exist on disk, but is created from git. Thus, it is given a special URI scheme `diffview://` to distinguish it from real files.

You won't be able to use LSPs with these temporary buffers. Not even in single-file mode. Because, as far as I'm aware, LSPs require the file to exist on disk.

However, LSPs do work in diffview in the diff buffers showing the local state of the file. That is the right side of the diff, when diffing a non-range git rev, or doing something like:

```
:DiffviewOpen feat/example-rev...HEAD --imply-local
```

<sup>Read more about `--imply-local` at `:h :DiffviewOpen`.</sup>

The files under "Staged changes" will never show the local state of the file, because that's a diff between HEAD on the left, and the staged state on the right.

> However in diffview the buffer has a very different name 
`diffview:///home/user/project/.git/:0:/src/main/java/com/package/name` (note even the fname is missing at the end)

Are you sure you didn't just `expand("%:p:h")`? The `:h` modifier would give you this path, with the last path component removed.

**Comment by asmodeus812** [comment]
Hmm, weird that, i am actually able to use lsp client in diff view mode, i have other normal servers which are setup through nvim lsp config suh as clangd which can be used in the diff view mode - i am able to fetch diagnostics, symbols etc in the actual diffs - working on the current file only of course (the prev diff, the left side does not which is fine). I want to achieve a similar result with jdtls which has a different way of setting up and attaching itself - using FileType event, and callback to attach to the buffer, but resolving the root from that path

**Comment by sindrets** [comment]
@asmodeus812 Yes, like I explained, LSP should work normally for the actual local version of a file. But the example you used was not the actual local version of the file. It was the representation of the staged version of the file.

To be very clear:

#### LSP should work normally on the right side of the diff  for the entries in this section:

![image](https://user-images.githubusercontent.com/2786478/179256856-9a29f779-26ef-4ad8-97d9-1346e9b7c547.png)

#### LSP is not gonna work for the entries in this section:

![image](https://user-images.githubusercontent.com/2786478/179256899-32835e2f-80e6-456e-abd6-1cb67483be7f.png)

**This is assuming that you haven't passed any arguments to `:DiffviewOpen` that would make the right side of the diff become represented by some other git revision.**

**Comment by asmodeus812** [comment]
That is what i was saying, the right-hand side works fine, which is okay. So for anyone wondering, what i did in the end is just attach to an already existing lsp client session (if such exists). 

```Lua
 for _, buf in pairs(vim.fn.getbufinfo({bufloaded=true})) do
    if api.nvim_buf_get_option(buf.bufnr, 'filetype') == '${your-file-type}' then
      local clients = lsp.buf_get_clients(buf.bufnr)
      for _, client in ipairs(clients) do
        if client.config.name == '${target-client-name}' then
          lsp.buf_attach_client(bufnr, client.id)
        end
      end
    end
  end
```
