### ISSUE TITLE
[feature request] Callback/Keybinding for DiffviewClose

### ISSUE THREAD

**Issue by francisco285** [sindrets/diffview.nvim#18]
So we could use something like:
``` lua
local cb = require('diffview.config').diffview_callback

require('diffview').setup({
  key_bindings = {
    view = {
      ['<leader>c'] = cb('diffview_close'),
      -- ...
    },
    file_panel = {
      ['<leader>c'] = cb('diffview_close'),
      -- ...
    }
  }
})
```

To would avoid the need of creating a normal ("global") keybinding to execute `:DiffviewClose` (which makes sense because we only need to run this when we're using diffview).

Awesome plugin btw

**Comment by sindrets** [comment]
@francisco285 this is partly my fault because I should have been clearer about this in the README, but you can set any custom normal mode mappings you want in those config tables. The callback is just a convenience. Just copying an answer I gave in a similar issue:

> I think I could have been clearer about it in the documentation, but the callback used in the configuration is really just a convenience. It's just a `string.format` under the hood and it produces something like: 
> 
> ```
> :lua require'diffview'.on_keypress('select_next_entry')<CR> 
> ```
> 
> The key binding tables' keys and values are just the `lhs` and `rhs` of `nvim_buf_set_keymap`. So you can set any custom normal mode mappings you want. Like:
> 
> ```lua
> -- ...
> file_panel = {
>   -- other maps...
>   ["<leader>c"] = ":MyCustomMap",
> }
> ```

So for you that would be something like:

```lua
view = {
  -- ...
  ["<leader>c"] = ":DiffviewClose",
}
```

(Also worth noting: `:tabc` does exactly the same thing as `:DiffviewClose`, except `DiffviewClose` only closes the tabpage if it is a Diffview. But that last part doesn't matter for a mapping like this.)

**Comment by francisco285** [comment]
It works, thanks!
