### ISSUE TITLE
`DiffviewOpen` and `DiffviewClose` merge into one command `DiffviewToggle`

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#188]
Then user could save one shortcut to open and close diffview~

May set a `filetype` to the buffer open by `Diffview`? Then can perform actions as per to the `filetype`

**Comment by sindrets** [comment]
@LintaoAmons Try something like this:

```lua
vim.api.nvim_create_user_command("DiffviewToggle", function(e)
  local view = require("diffview.lib").get_current_view()

  if view then
    vim.cmd("DiffviewClose")
  else
    vim.cmd("DiffviewOpen " .. e.args)
  end
end, { nargs = "*" })
```

---

> May set a `filetype` to the buffer open by `Diffview`? Then can perform actions as per to the `filetype`

If you're referring to the diff buffers, then the answer is no. The diff buffers will have whatever filetype they would normally have outside of Diffview. Otherwise they wouldn't be syntax highlighted.

However all the panels have their own filetype. And all buffers created by Diffview have a very specific naming scheme. You can use the buffer names to target them from auto commands etc.

Some example paths:

```
diffview:///some/path/to/repo/.git/{GIT_SHA}/path/inside/the/repo/file.txt
diffview:///panels/{ID}/DiffviewFileHistoryPanel
diffview:///some/path/to/repo/.git/log/{ID}/commit_log
```

If you're trying to run auto commands when opening the diff buffers, you should look at the `:h diffview-config-hooks`. Specifically the `diff_buf_read` and `diff_buf_win_enter` hooks. These hooks will easily let you set local options in the diff buffers etc. and there are examples in the docs.

**Comment by LintaoAmons** [comment]
Thanks for your throughful explanation! Really appreciate

**Comment by sindrets** [comment]
Closing as I've already explained why I don't think a toggle command would be a good fit in #11. There are multiple solutions in that thread, and now also one solution in this one.

Let me know if you have any more questions.
