### ISSUE TITLE
[Bug] Setting winbar causes `Vim:E36: Not enough room` error when closing DiffView

### ISSUE THREAD

**Issue by akinsho** [sindrets/diffview.nvim#193]
Since the recent refactor of Diffview to accomodate different layouts, I've been seeing the following error when trying to close diffview.

```
Error executing Lua callback: .../pack/packer/opt/diffview.nvim/lua/diffview/git/file.lua:315: Vim(append):Error executing lua callback: /Users/akin/.dotfiles/.config/nvim/plugin/winbar.lua:10
7: Vim:E36: Not enough room
```

This is directly related to showing a winbar in a diff window and that breaking when closing the diffview tab for some reason.

I set my winbar using
```lua
for _, win in ipairs(api.nvim_tabpage_list_wins(0))
  local buf = api.nvim_win_get_buf(win)
    local ft, bt = vim.bo[buf].filetype, vim.bo[buf].buftype
    local is_diff = vim.wo[win].diff
    if
      not is_diff
      and not vim.tbl_contains(blocked, ft)
      and fn.win_gettype(win) == ""
      and bt == ""
      and ft ~= ""
    then
      vim.wo[win].winbar = '%{%v:lua.as.ui.winbar.get()%}'
    elseif is_diff or not vim.tbl_contains(allowed, ft) then
      vim.wo[win].winbar = nil
    end
  end
end
```

I've worked around this by triggering the function in diff view autocommands e.g.
```lua
    event = 'User',
    pattern = { 'DiffviewDiffBufRead', 'DiffviewDiffBufWinEnter' },
```
And this seems to ensure there is no winbar in diff view window, but I still see this error when exiting diff view. It seems maybe a very small window is being created, very briefly 🤷🏿 not too sure.

**Comment by sindrets** [comment]
@akinsho Could you try [this branch](https://github.com/sindrets/diffview.nvim/tree/fix/193) and see if the problem is solved?

The plugin does indeed open a very small (1x1) floating window very briefly in order to restore window-buffer local options of all the files that weren't created by the plugin. But the window is opened with [`noautocmd` set](https://github.com/sindrets/diffview.nvim/blob/8d58e26049709f3a114e297a216201940ae5a5a6/lua/diffview/utils.lua#L1135) and [`eventignore` is used to avoid triggering most of the window / buffer related auto commands](https://github.com/sindrets/diffview.nvim/blob/8d58e26049709f3a114e297a216201940ae5a5a6/lua/diffview/utils.lua#L96-L110). And it seems like the winbar setup in your dotfiles [should ignore floating windows](https://github.com/akinsho/dotfiles/blob/a009ddb5eace2a7204baf930756422a43f3bcfd8/.config/nvim/plugin/winbar.lua#L104). So I don't really know what's going on here. But I still use 0.7 as my daily driver so I haven't really played around with the winbar yet.

**Comment by akinsho** [comment]
@sindrets thanks for the quick fix, I just tried out that branch, and it does seem to fix the issue I was having. As for the behaviour of why it's causing this error, I believe there are still discussions about whether winbar should be omitted from floating windows by default. I personally think if the window is minimal they should be, but core still needs to decide https://github.com/neovim/neovim/issues/19464.

Re. the autocommands and eventignore no idea why it's still triggering my autocommand. I tried messing around with autocommands before opening this issue, but nothing seemed to help. I think what the issue indicates is that the setting carries across from the previous window maybe but it's shouldn't be present there at all anyway since I don' have a global winbar set.
