### ISSUE TITLE
[Feature] blame view

### ISSUE THREAD

**Issue by arashm** [sindrets/diffview.nvim#196]
Great plugin! It would be nice to get a blame view the same as the one Fugitive provides. Diffview seems to have all the bolts and buts to implement such a feature.

<img width="827" alt="Screen Shot 2014-02-07 at 3 38 20 PM" src="https://user-images.githubusercontent.com/849640/187186794-6309bca5-6311-4e9d-85bb-14ec8173a4c4.png">
(screenshot is not mine)

**Comment by sindrets** [comment]
@arashm Could you please elaborate on what you would expect from a git-blame implementation in diffview? What would diffview offer here that Fugitive does not already?

**Comment by arashm** [comment]
Diffview generally has a better view and management of panes. vgit also provides something similar but with very limited functionality. In the case of vgit, the blame pane doesn't have colouring, navigating through blame lines is finicky, you can't select lines, and many more...
Not sure if it's a valid point, but I like to have a single source for diffs, so I have a unified configuration and shortcuts. But if you think it's not the purpose of diffview, then I close this.

**Comment by sindrets** [comment]
@arashm Sorry for not getting back to you on this sooner.

If your desire for a git-blame implementation in diffview only comes from a preference for having everything in one plugin, then I'm not interested in implementing this. You still haven't been clear about what diffview can bring to the table here. I personally think Fugitive's git-blame solution is essentially perfect (it's what I use), and I'm certainly not interested in just cloning Fugitive functionality. Especially when there isn't even a performance incentive to do so, which I don't believe there is in this case.

The intention for this plugin is to be focused on being a good git diff viewer, not to be a complete git wrapper. For that reason, this issue is a "won't-fix" for now. I'm of course still willing to discuss this further if you, or anyone else brings something more substantial in terms of what an implementation might look like (either in terms of layout, what components it would involve, and / or in terms of what the workflow might look like). It would have to involve a diff in some shape or form (not just the output of `git show <REV>`, as Fugitive already does this).

**Comment by arashm** [comment]
Diffview.nvim generates a better side-by-side diff. What I'm looking for here is to get a diff view of Diffview.nvim when I want to see the changes of a commit I selected in the blame. When I open the git blame view on Fugitive, and press `<CR>`, it just shows me a plane patch of the commit. I tried and searched, but I couldn't figure out if there's a way to customize Fugitive to run `DiffviewOpen <REV>`, instead of the simple `git show <REV>`.

**Comment by sindrets** [comment]
> I tried and searched, but I couldn't figure out if there's a way to customize Fugitive to run `DiffviewOpen <REV>`, instead of the simple `git show <REV>`.

@arashm That part is at least simple. The commit SHA is right there in the blame buffer. You just need to yank it in a mapping. Try something like this:

```vim
" {NVIM_CONFIG}/after/ftplugin/fugitiveblame.vim

" Open diffview for the commit under the cursor
nnoremap <buffer> <C-M-d> <Cmd>exe 'norm! 0"xyiw' <bar> wincmd l <bar> exe 'DiffviewOpen ' . getreg("x") . '^!'<CR>
" Open file history for the current file, from the commit under the cursor
nnoremap <buffer> <C-M-h> <Cmd>exe 'norm! 0"xyiw' <bar> wincmd l <bar> exe 'DiffviewFileHistory % --range=' . getreg("x")<CR>
```

You can of course also override the `<CR>` mapping if you want.
