### ISSUE TITLE
[bug] Scroll position is lost when leaving the tab and the main window is `null`.

### ISSUE THREAD

**Issue by th4s** [sindrets/diffview.nvim#197]
When I have a diff open in a tab, sometimes I switch to another tab to get some context information from other parts of the code. When I switch back the diff is scrolled to the beginning of the file. Would be cool if the scroll position is remembered.

**Comment by sindrets** [comment]
@th4s I can't reproduce this. The plugin does not change the cursor position of the diff buffers when leaving / entering the tab page.

How do you switch back to diffview's tab page? Do you delete the buffer in question in the other tab? Because this would make you loose the cursor position. Buffers for local files are the same both inside diffview's and outside. So if you delete a buffer that's in use in a diffview, it's gonna have to load that buffer again. At that point the cursor is probably back at the top.

If that was not the problem I'm gonna need steps for reproduction.

**Comment by th4s** [comment]
I just cycle through the tabs with 'gt'. I noticed now, that this only happens for diffs on deleted files. When files have been added or modified it works fine.

I am using:

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui

**Comment by sindrets** [comment]
@th4s Ah, I see. This is happening due to the cursor- and scroll binding. We have to use an actual buffer to represent deleted files, and all buffers need to have at least one line. When you enter a diffview the right diff window briefly receives focus in order to sync the scroll of the two windows. When this right window contains the null file with only one line, the scroll position is determined to be at the top of the file.

I suppose we could circumvent this by using the diff buffer with the highest number of lines when performing the scroll sync.
