### ISSUE TITLE
Wrapped lines alignment

### ISSUE THREAD

**Issue by jgarciaokode** [sindrets/diffview.nvim#198]
Hello!

First of all, thank you for this awesome plugin! 

I noticed something that vscode manages to handle pretty effectively and was wondering if there could be a solution

Notice how line 7 in left split is one line down compared to right split

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/79897391/187546185-933d9980-6e55-4f97-a163-5f001402235a.png">

In vscode is properly aligned, i guess they add extra "blank" lines

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/79897391/187546500-74746ffc-e46e-4b43-8ad8-30c1fea3dfe6.png">

I already tried with every diffopt combination and didn't manage to solve it

Thank you in advanced

**Comment by Gelio** [comment]
I suppose this could be solved by https://github.com/neovim/neovim/pull/14537 which would match the lines in a better way.

Aside from that, I am not sure if a Lua plugin can help with diff buffers. They rely on the core (neo)vim functionality and plugins have little control over the way the diff is presented, as far as I know. This is the conclusion I came to in #9.

**Comment by sindrets** [comment]
@jgarciaokode There is realistically not much I can do about this here. I don't want to start inserting and managing virtual lines in the diff buffers in order to align wrapped lines. In my opinion this should be addressed as a feature request upstream.

There are a few half-measures you could consider though:
- Disable `wrap` in the diff buffers.
- Close the file panel while viewing diffs. This will give you some additional horizontal space.
- Use the horizontally split layout by setting `set diffopts+=horizontal`. This would give you a lot more horizontal space for each diff window.

@Gelio Unfortunately I don't thing the linked PR will help with this problem. The problem is that the diff-mode only operates on actual lines, and does not account for offsets produced by wrapped lines.

**Comment by Jendker** [comment]
Do you think there is a way to automatically disable wrap in the diff buffers but keep wrap as default otherwise?

**Comment by sindrets** [comment]
@Jendker Yes. See the `diff_buf_read` hook example under `:h diffview-config-hooks`.
