### ISSUE TITLE
`DiffviewOpen` does not expand relative paths correctly.

### ISSUE THREAD

**Issue by zjp-CN** [sindrets/diffview.nvim#199]
For `salsa/book/src/tutorial/debug.md`, where `salsa` is the project directory:

In the root (`nvim book/src/tutorial/debug.md`), `:DiffviewOpen 0f7a8c33..master -- %` is successful to show the diff:
```
/rust/github/salsa
Changes (1)
   book/src/tutorial
M      debug.md 2, 22

Showing changes for:
0f7a8c33..master
book/src/tutorial/debug.md
```

But in `salsa/book` dir (`nvim src/tutorial/debug.md`), `:DiffviewOpen 0f7a8c33..master -- %` and `:DiffviewOpen 0f7a8c33..master -- src/tutorial/debug.md` show:
```
/rust/github/salsa
Changes (0)

Showing changes for:
0f7a8c33..master
src/tutorial/debug.md
```

In this case, `:DiffviewOpen 0f7a8c33..master -- book/src/tutorial/debug.md` remains correct.

https://asciinema.org/a/5bYSnvIdrpsdxKZIjR5AYHXdm

**Comment by sindrets** [comment]
@zjp-CN The path should be relative to the top-level of the work tree, or absolute. You can use `%:p` in this scenario. This expands to the absolute path.

**Comment by zjp-CN** [comment]
> You can use `%:p` in this scenario.

Cool, it works!

But the syntax `%` in DiffviewFileHistory always works. So why do they differ? 

I've also noticed the DiffviewOpen needs `-- %`  but DiffviewFileHistory simply needs `%`. Is it intentional to make them different?

**Comment by sindrets** [comment]
> But the syntax % in DiffviewFileHistory always works. So why do they differ?

@zjp-CN You're right, that is weird. I see now that for file history I made the plugin expand the paths in a more intelligent way. I'll see if I can address this soon such that both commands treat paths the same way.

> I've also noticed the DiffviewOpen needs `-- %` but DiffviewFileHistory simply needs `%`. Is it intentional to make them different?

The commands have different call structures:

```vimhelp
:DiffviewOpen [git-rev] [options] [ -- {paths...}]
:[range]DiffviewFileHistory [paths] [options]
```

`DiffviewOpen` needs the end-of-options separator (`--`) to avoid ambiguity between git revs and paths. This should also be familiar from various git sub commands. Although git is quite good at distinguishing between these two types of arguments, but if you've used git for a while you've probably had it complain about "ambiguous arguments" at some point. The end-of-options solves this.

`DiffviewFileHistory` doesn't need it at the moment because revs are specified with flag options.
