### ISSUE TITLE
Diff panes behave weird with popups

### ISSUE THREAD

**Issue by folke** [sindrets/diffview.nvim#2]
First of all, thank you very much for making this!

When the cursor is in one of the diff buffers, then all popup windows like Telescope, or WhichKey, also get a weird diff view.

Do you have any idea how to fix this?

Focusing the file list and then opening a poup is ok

**Comment by sindrets** [comment]
Yes, I'm aware of this issue, but unfortunately I don't know how to proceed here. We have a [similar problem in NvimTree](https://github.com/kyazdani42/nvim-tree.lua/issues/290). Basically it's default vim behavior: when creating a new window, vim copies all settings from the current window. That includes `diff`. 

It's complicated, because we can't just save all the settings from the first window we see, as many people use i.e. some sort of dashboard plugin, and that would work very inconsistently with lazy loading. 

I'll see what I can do, I should at least be able to disable `diff` for any newly created windows while in a Diffview. But if anyone has any knowledge about how to properly tackle this problem, please share.

**Comment by folke** [comment]
Thanks!
