### ISSUE TITLE
Neogit integration

### ISSUE THREAD

**Issue by TimUntersberger** [sindrets/diffview.nvim#20]
Hello!

I really like the look of your plugin so I would like to integrate your plugin with [neogit](https://github.com/TimUntersberger/neogit).

Some things are still a bit unclear for me so I'd appreciate it if you could help me with a few things:

* Is there a way to get notified when something happens? 
  * for example you commit a change; how can I get notified?
* Are you going to provide an API which can be used by other plugins? 
  * I am mainly looking for ensurance that the API won't have any breaking changes too often
* Could you support feeding the plugin the files myself? Right now opening the diff is a bit too slow for my taste and neogit already has the information when trying to open the diff.
* Is any merge conflict support planned or even wanted?

**Comment by sindrets** [comment]
@TimUntersberger Hello! Integration sounds interesting, and I'm willing to work with you to get this to work.

> - Is there a way to get notified when something happens?
>    - for example you commit a change; how can I get notified?

Diffview does not handle committing nor staging, so there is simply nothing for diffview to notify plugins about in that regard. I want to leave such functionality to git wrappers. There are currently 3 things that cause a diffview to update, which is:

- Every time you enter a Diffview
- On `BufWritePost`
- On `FugitiveChanged`

Updates are not run unless the current tabpage is a Diffview. Update on `FugitiveChanged` is just a nicety, fugitive is not required. Other than that updates can be triggered manually with a key binding, or by calling the exposed `View:update_files()` method. My point being, integrating plugins would have to notify diffview, not the other way around. 

> - Are you going to provide an API which can be used by other plugins? 

I'm willing to implement one, but I need to know what you would expect from the API. What sort of hooks and/or functions do you need?

> - I am mainly looking for ensurance that the API won't have any breaking changes too often

I can give you my assurance that I won't make breaking API changes without notifying you about it, and giving you time to accommodate the changes. I want to also note that if you provide a decent spec for what you need out of the API, there won't be a need to make breaking changes.

> - Could you support feeding the plugin the files myself?

Sure, but what exactly do you mean? I can see at least three different ways this could be implemented:

- Do you just want to provide a list of paths?
- Do you want to provide a list of objects that contain information about: path, number of insertions, number of deletions, git status. This would let you skip a number of the shell calls I'm making, which would improve performance.
- Do you want to provide custom `FileEntry` objects, and handle everything like buffer creation, loading, and disposing yourself? I don't know if want to support this. But if it were to be done, your custom `FileEntry` objects would have to fully implement the interface of my `FileEntry` class.

> Right now opening the diff is a bit too slow for my taste

I assume you are referring to buffer creation of files from git history being slow? I agree. The current way it is done was kind of just something that works. But I already have plans in mind for how to improve it.

> Is any merge conflict support planned or even wanted?

A merge tool is something I have been thinking of since the start of the project. So yes, it is wanted, and I want to get around to implementing it once I get some more time.

**Comment by TimUntersberger** [comment]
> I'm willing to work with you to get this to work

Thank you!

> Diffview does not handle committing nor staging, so there is simply nothing for diffview to notify plugins about in that regard. I want to leave such functionality to git wrappers

Ah so `diffview` is more a wrapper around `:h diff` than anything else? Very cool!

> My point being, integrating plugins would have to notify diffview, not the other way around.

I think just overriding the keybindings on the `neogit` side should be enough now that I thought about it some more.

> I'm willing to implement one, but I need to know what you would expect from the API. What sort of hooks and/or functions do you need?

After looking at the code some more I think just returning the created view in the [open function](https://github.com/sindrets/diffview.nvim/blob/272a474abf7d1b64d5dcaf21f80d6fdc7b623ead/lua/diffview.lua#L19) should be enough for now.

> Sure, but what exactly do you mean?

My ideal vision is that I would call the `open` function with a list of files where I would provide the `left` and `right` side content of the diff and any other metadata you need for the files view. So I guess it is more a mix of the 2. and 3. option if you know what I mean. If it is still a bit unclear I can provide a small example on how I would want to use it ideally.

> A merge tool is something I have been thinking of since the start of the project. So yes, it is wanted, and I want to get around to implementing it once I get some more time.

If the `diffview` integration works well, I would gladly help you with the merge stuff as `neogit` would benefit from this too.

**Comment by sindrets** [comment]
> My ideal vision is that I would call the open function with a list of files where I would provide the left and right side content of the diff and any other metadata you need for the files view. So I guess it is more a mix of the 2. and 3. option if you know what I mean. If it is still a bit unclear I can provide a small example on how I would want to use it ideally.

I think I understand. Could you give me an example of how you would expect the struct to look? My suggestion is something like this:

```teal
local record FileData
    path: string -- Path relative to git root
    left_data: {string} -- List of lines that should go in the left diff buffer.
    right_data: {string} -- List of lines that should go in the right diff buffer.
    record GitStats
        additions: integer
        deletions: integer
        status: string -- The git status symbol (M, A, ?, etc...)
    end
end
```

**Comment by TimUntersberger** [comment]
That would work!

**Comment by Gaurang033** [comment]
could someone how to use this, how. that code is merged. i will looking for exactly same thing.
