### ISSUE TITLE
Register based lua diff tool?

### ISSUE THREAD

**Issue by jweckman** [sindrets/diffview.nvim#215]
I would like to have a lua plugin that allows me to compare arbitrary registers using a function. Does anyone on here know a good way to do it or could this plugin perhaps have that as a feature?

Easiest workflow would be to compare the "+" and "*" registers for quick diffing clipboard/visual selection in e.g. single functions or classes from files that are not in the same repo. I got fairly far making the lua plugin myself but then i thought that it would be best to use the UI of this plugin if possible.

Concretely speaking, i'm basically looking to combine the following code snippets into a plugin (best to make function take registers as arguments but you get the idea):

Lua starting point:

```lua
local M = {}

local function get_reg(char)
	return vim.api.nvim_exec([[echo getreg(']]..char..[[')]], true):gsub("[\n\r]", "^J")
end

M.compare_clipboard = function()
    local r_plus = get_reg("+")
    local r_star = get_reg("*")
    local bp = vim.api.nvim_create_buf(false,false)
    local bs = vim.api.nvim_create_buf(false,false)
    vim.api.nvim_set_current_buf(bp)
    local lines = {
        "line1",
        "line2",
    }
    vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
end

return M
```

Working vimscript implementation

```vim
let g:diffed_buffers = []

function DiffText(a, b, diffed_buffers)
    enew
    setlocal buftype=nowrite
    call add(a:diffed_buffers, bufnr('%'))
    call setline(1, split(a:a, "\n"))
    diffthis
    vnew
    setlocal buftype=nowrite
    call add(a:diffed_buffers, bufnr('%'))
    call setline(1, split(a:b, "\n"))
    diffthis
endfunction
```

Any kind of input on best practice would be much appreciated :)

**Comment by jweckman** [comment]
Wow! Thank you so much!

I actually managed to make a clumsy version myself and now i'm very happy to see a much improved one that can be used by anyone.

For anyone who prefers vertical split you only need to change is "aboveleft" to "vertical" and you should be good to go. Sample remap in lua if you want to compare "a" and "+" registers instead:

`vim.api.nvim_set_keymap('n', '<leader>cc', ":RegDiff + a<CR>", { noremap=true, silent=true })`

**Comment by sindrets** [comment]
@jweckman  you're welcome!

> For anyone who prefers vertical split you only need to change is "aboveleft" to "vertical" and you should be good to go.

`aboveleft` is better, because that way it's controlled by your `:h 'diffopt'`. If you prefer vertical diff splits you should add `vertical` to your `diffopt`:

```lua
vim.opt.diffopt:append("vertical")
```

Also if you only use `vertical` without `aboveleft` then the diff windows would be arranged opposite of what you passed in as arguments. I.e. `:RegDiff a b` would result in register `b` being on the left and `a` on the right, which is confusing in my opinion. 

Note that you can also combine `:h command-modifiers`, so you could do both `:aboveleft vertical RegDiff`. This would *force* a vertical diff split (overriding `diffopt`) and arrange the diff windows correctly with regards to the order of the arguments.

Just a friendly tip regarding the keymap: `:h vim.keymap.set()` is more ergonomic to use. Among other things this API has `noremap` inverted as `remap` (as it should be) making mappings non-recursive by default. Also it's a good idea to use the `<Cmd>` pseudo key when you're creating mapping for Ex commands. This way the command is run directly rather then feeding keys, which is what you are currently doing. Example:

```lua
-- The equavalent of the mapping you suggested, but using `vim.keymap` and `<Cmd>`
vim.keymap.set("n", "<leader>cc", "<Cmd>RegDiff + a<CR>", { silent = true })
```
