### ISSUE TITLE
[Question]: Using diffview.nvim as a git mergetool

### ISSUE THREAD

**Issue by mrjones2014** [sindrets/diffview.nvim#226]
I've got `diffview.nvim` configured as my `git mergetool` via the following lines in my git config:

```gitconfig
[merge]
  tool = nvim
[mergetool "nvim"]
  cmd = nvim -f -c \"DiffviewOpen\"
[mergetool]
  prompt = false
```

This works super well, with one caveat: the `git mergetool` command expects conflicts to be resolved one file at a time, e.g. open neovim, resolve conflict in a single file, close neovim, `git mergetool` continues, opening the next file in neovim.

This somewhat conflicts with what I'd see as the more typical workflow: open neovim to diffview, resolve all conflicts, exit neovim, done.

However, when you do this, `git mergetool` continues opening neovim for each conflicted file, and if you just quit it says "file appears unchanged, were conflicts resolved?" and you just have to manually tell `git`  that "yes, I resolved the conflict already".

Do you know of anyway to make Neovim tell `git mergetool` "hey we've resolved all the files, you can stop now"?

**Comment by gegoune** [comment]
https://github.com/sindrets/diffview.nvim/pull/205#issuecomment-1236414378

I asked the similar question. :)

**Comment by mrjones2014** [comment]
I could always just resolve conflicts manually by opening Neovim and running `:DiffviewOpen` but my muscle memory is to type `git mergetool`.

Looking through the [`git-mergetool`](https://git-scm.com/docs/git-mergetool/) docs I'm not sure there's a way to accomplish what I'm asking for at all 🙁

**Comment by gegoune** [comment]
Perhaps there could be some `--single-file-mode` flag for `DiffviewOpen` which would only diff single file allowing for `git mergetool` to work. @sindrets was open to discussion on that subject so maybe given enough interest such functionality might get implemented one day.

**Comment by sindrets** [comment]
I don't think that's possible in any clean way. You could make a script that essentially tricks the git-mergetool into thinking all files have been dealt with. But this obviously has other problems. Among other things you wouldn't be able to abort the merge once you've opened the mergetool.

I feel like this is an XY problem. The git-mergetool was designed for a very specific workflow, and this cannot be conventionally configured. If the goal is to resolve the merge conflict in diffview, then I see no reason to jump through hoops in order to make git-mergetool and diffview cooperate (especially since git-mergetool is not designed to be able to do this).

Just begin the merge, producing the set of conflicted files. Then open diffview and resolve the conflict. Finally, stage and `git merge --continue` to end the conflict.

If availability from your shell is a concern you could of course just set up an alias like:

```bash
alias mergetool='nvim -c DiffviewOpen'
```

**Comment by mrjones2014** [comment]
Oh nice. I could even do a git alias to keep my muscle memory.

gitconfig:
```gitconfig
[alias]
  mergetool = "!nvim -c DiffviewOpen"
```
