### ISSUE TITLE
[Feature?] git difftool / mergetool integration

### ISSUE THREAD

**Issue by XobSod** [sindrets/diffview.nvim#228]
Hello,

Sorry for noob question, but I am just starting with neovim and I don't quite know it this is possible.

Is it possible to somehow configure `git` to use diffview as its difftool / mergetool? What I mean is I would like to run in terminal a git command for example `git difftool HEAD~3` and have vim with diffview opened. Or the same when in merge with conflicts, run `git mergetool` and have vim with diffview opened with merge displayed.

**Comment by sindrets** [comment]
@XobSod This was recently discussed in #226. Please read that thread and then let me know if anything is still unclear.

**Comment by XobSod** [comment]
Thank you. I will have to test it and somehow accommodate ;)

**Comment by sindrets** [comment]
There's nothing to accommodate. It's an XY problem. You're essentially asking "how do I use X to do Y?", when what you should be asking is just "how do I do Y?". Git-difftool and git-mergetool are not the right tools to solve your problem. If the actual intention is "open diffview directly from the shell", then the solution is already mentioned in the thread I linked: create a shell alias or a git alias. This way you're addressing the problem directly, rather than going the detour through git-difftool and git-mergetool, which are tools that are not designed to do the thing you're trying to accomplish.
