### ISSUE TITLE
How to disable folding?

### ISSUE THREAD

**Issue by lopi-py** [sindrets/diffview.nvim#236]
I feel that folding is wrong, is this intended?
![image](https://user-images.githubusercontent.com/70210066/196019375-1aecb766-7ca4-442b-8624-224312cce810.png)
![image](https://user-images.githubusercontent.com/70210066/196019379-544cfaa2-2dd0-4002-8ed9-f8d2150f1429.png)

**Comment by sindrets** [comment]
If you actually want to disable folds entirely, then disable `'foldenable'` in the diff buffers. There are examples in the docs on how to set local options in diff buffers. See the example under `:h diffview-config-hooks`.

But it seems like what you actually want is to increase `'foldminlines'`. This will make it so that no fold can span less then the set number of minimum lines.

**Comment by lopi-py** [comment]
Thanks! I noticed that diff fold lines that arent changed given a context that can be set `set diffopt=context:5` thats why I have some lines folded and others no, because of the context, I set it to 1 and works as I want 😄
