### ISSUE TITLE
[Question] Is there a way to track down the diffs only for a PR

### ISSUE THREAD

**Issue by MikePresman** [sindrets/diffview.nvim#240]
Is it possible currently to view the diffs only for one specific PR.

E.g.
PR "feat: ABC"
has 4 commits.
Can I see only the diffs of the files changed in that PR - irrespective of the commits. I want to avoid commits here because the last commit may override the changes of the first commit - rendering my review of the first commit useless - it was overwritten.

I.e. Can I see the diff of only the scope of an entire PR and it's files' changed?

Is this even possible in the scope of git?

Thanks

**Comment by sindrets** [comment]
If the PR branch has not been merged yet, then it's very simple. Just use the symmetric difference notation (triple dot):

```
:DiffviewOpen origin/main...topic/branch
```

If the branch has already been merged then symdiff won't help because the commits now exist on both the branches. In that case you're gonna have to find the fork point of the two branches. If your local ref logs contain enough information about the branch (i.e. you created it locally yourself) you might have luck with `git merge-base --fork-point origin/main topic/branch`. Otherwise the easiest way is honestly to look at the commit graph:

```console
$ git log --oneline --graph origin/main
```

Then find the fork point, and do:

```
:DiffviewOpen FORK_POINT^..topic/branch
```

Note also that if you are checked out on `topic/branch`, you can omit its name in all these use-cases. Omitting either side of a git rev range falls back to `HEAD`.

**Comment by MikePresman** [comment]
> If the PR branch has not been merged yet, then it's very simple. Just use the symmetric difference notation (triple dot):
> 
> ```
> :DiffviewOpen origin/main...topic/branch
> ```
> 
> If the branch has already been merged then symdiff won't help because the commits now exist on both the branches. In that case you're gonna have to find the fork point of the two branches. If your local ref logs contain enough information about the branch (i.e. you created it locally yourself) you might have luck with `git merge-base --fork-point origin/main topic/branch`. Otherwise the easiest way is honestly to look at the commit graph:
> 
> ```
> $ git log --oneline --graph origin/main
> ```
> 
> Then find the fork point, and do:
> 
> ```
> :DiffviewOpen FORK_POINT^..topic/branch
> ```
> 
> Note also that if you are checked out on `topic/branch`, you can omit its name in all these use-cases. Omitting either side of a git rev range falls back to `HEAD`.

Thank you, :DiffviewOpen origin/main...topic/branch does exactly what I want.
And I appreciate the tip for if the commit is merged.

Feel free to close - and as always thanks for the awesome plugin.
