### ISSUE TITLE
Bug: Cannot start Diffview, Error for no directory found

### ISSUE THREAD

**Issue by chrisgrieser** [sindrets/diffview.nvim#242]
I installed diffview.nvim, and when trying to run any of its commands, I get this error message, followed by a three-way-split without a diff view.

<img width="1564" alt="Pasted image 2022-11-09 23 56 46" src="https://user-images.githubusercontent.com/73286100/200960038-9ca0998f-1212-445e-b91a-5cb1dc9c6577.png">

```
latest diffview.nvim
latest plenary.nvim
git 2.37.1
macOS 13.0 (M1)
neovim 0.8.0 (homebrew)
```
`cdpath` options has not been changed in my config ( it's still the default `,,`)

**Comment by sindrets** [comment]
@chrisgrieser seems like you have an auto command or plugin that tries to auto-cd into the directory of an opened buffer. This fails for diffview buffers because their names are URI's, not real paths. If you set up this auto command then you should check whether a buffers name is a real path before trying to cd into it.

If this does not help you solve it, then you need to provide a minimal config that makes this reproducible. [Here's a template](https://gist.github.com/sindrets/3e671e79ce4566667f9ec176786dfadd).

**Comment by chrisgrieser** [comment]
> seems like you have an auto command or plugin that tries to auto-cd into the directory of an opened buffer.

ah yes, I have indeed such an autocmd. And since I actually do not need it anymore, this was easy to fix 😅 

Thanks, for the quick support!
