### ISSUE TITLE
Is it possible to open diffview in it's own buffer?

### ISSUE THREAD

**Issue by Liverm0r** [sindrets/diffview.nvim#246]
Problem:
I use [bufferline](https://github.com/akinsho/bufferline.nvim) plugin to show buffers as tabs. When I use `:DiffViewOpen ...`, no new buffer is created, and `diffview` is shown inside the current buffer.

**Comment by sindrets** [comment]
@Liverm0r Hm, seems like perhaps you're confusing some vim terminology here? I use bufferline too. It does not show buffers as tabs. Tab pages in vim refer to a collection of windows. A buffer is the in-memory text of a file. A window is a viewport on a buffer.

When you call `:DiffviewOpen`, a view is opened in a new *tab page*. It does not take over the current buffer. You can return to your last accessed tab page with the default nvim mapping `g<Tab>`.

**Comment by Liverm0r** [comment]
As I get it, bufferline with `options.mode="buffers"` shows each buffer in the upper line, where vim shows tabs by default.

When I used the command `DiffViewOpen`, I thought that no new buffer was created because:
1. `:ls` doesn't show a buffer for diffview.
2. bufferline substitute current buffer with diffview (without bufferline enabled I get diffview opened inside new vim tab).

https://user-images.githubusercontent.com/14236531/201342711-8ddad130-4452-4c4b-ae05-587030387726.mov

**Comment by Liverm0r** [comment]
> a view is opened in a new tab page

Is it possible to open this view inside new buffer, or any other solution to show it without a conflict with bufferline as I showed on the video above?

**Comment by sindrets** [comment]
Diffview's buffers are unlisted. If you want to list them with `:ls` you need to add the exclamation mark: `:ls!`. But I don't understand what you're trying to accomplish here.

> Is it possible to open this view inside new buffer, or any other solution to show it without a conflict with bufferline as I showed on the video above?

Again, this question seems misguided. Views consist of *many* buffers. The file panel has a buffer. The null buffer is a buffer (the empty buffers you're seeing when there's nothing to diff). Each version of a file in a diff has a buffer. That is both the old state and the new state. So the question doesn't make any sense.

There's no conflict with bufferline. You can see that bufferline displays diffview's tab page in the top right in your video. You see the numbers "1 | 2"? Those are actual tab pages. Collections of windows. It might perhaps help to think of these as what some other IDE's refer to as "workspaces".

Bufferline lets you more easily navigate buffers. However, it doesn't replace tab pages. Tab pages have a different use. Tab pages are a perfect fit for what we're using them for here in diffview: creating a user interface consisting of multiple windows and buffers. You can't get bufferline to list diffview's tab page as a buffer, because that's not what it is.

**Comment by Liverm0r** [comment]
Thank you, now it makes more sense. I guess I was confused because these views were unlisted.

**Comment by ogios** [comment]
you can separate buffers by tabs as to what bufferline.nvim README says, using [scope.nvim](https://github.com/tiagovla/scope.nvim)
