### ISSUE TITLE
Git diff using dandavison/delta?

### ISSUE THREAD

**Issue by MatthiasX86** [sindrets/diffview.nvim#25]
Have you considered using https://github.com/dandavison/delta for the git diff?

**Comment by sindrets** [comment]
If you're suggesting using delta for creating the diff buffers, then no, I haven't considered it because it's not feasible. I'm not generating the diff highlighting as is. The diffing is done by vim. Please see `:h diff-mode`.

Generating the diff output is not really possible at the moment, as i.e. there is no way to render deleted lines like they are being rendered in diff mode. Which means we would have to use something like blank lines with highlighting, which would cause all the line numbers to be wrong.

That being said, if you really want to use delta in vim diff mode, you can set your `diffexpr` to whatever you want. But vim still expects the output to be either ED style, or unified style, so I doubt you would get much out of it and it would probably be slower then using vim's internal diff which uses the xdiff library.
