### ISSUE TITLE
Opt out of bootstrap dependency check

### ISSUE THREAD

**Issue by sQVe** [sindrets/diffview.nvim#253]
_First of all, **thank you** for an excellent plugin! 🙌🏼_ 

---

👋🏼,

I use `packer` as my plugin manager and handle my dependencies by using the `module` option. I  feel that this is quite elegant since it allows me to load `plenary` asynchronously when needed and I do not need to list it as an dependency for multiple plugins.

This has worked like intended until I installed `diffview`, since it checks for the dependency during the bootstrap step and exist early if not found. This forces me to write: 
```lua
  use({
    'sindrets/diffview.nvim',
    after = 'plenary.nvim',
    requires = 'nvim-lua/plenary.nvim',
  })
```
when I really should be able to write (on my setup):
```lua
  use({
    'sindrets/diffview.nvim'
  })
```

Would it be possible to add some kind of option or something to opt out of dependency check? 😊 🙏🏼

**Comment by sindrets** [comment]
> First of all, thank you for an excellent plugin!

Glad to hear you find it useful!

---

I've been considering moving the dependency checking into a health-check instead regardless. It was originally added to the bootstrap step when plenary first became a dependency, in order to ease the transition for users. But that was a while ago, and I feel like it's safe to remove it from the bootstrapping step now.
