### ISSUE TITLE
Taking sponsors/tips?

### ISSUE THREAD

**Issue by davidatsurge** [sindrets/diffview.nvim#264]
I just realized that I use this plugin every day to make a living, it would be fair to throw a couple of dollars your way 😛.

**Comment by sindrets** [comment]
I'm immensely honored that you've taken an interest in supporting me, and I'm really glad to hear you find the plugin useful in your work!

I just began setting up Github Sponsors, but it's gonna take a couple of days for them to approve my account. I'll ping this thread once I get an update from Github.

Finally, I would like to emphasize that - while it's greatly appreciated - you should feel no sense of obligation to support me financially. This is not my job; I make and maintain developer tools because I enjoy doing it :)

**Comment by sindrets** [comment]
Github sponsors is now available from [my profile](https://github.com/sponsors/sindrets) and from this repository's sidebar :)
