### ISSUE TITLE
Diff splits are now horizontal by default

### ISSUE THREAD

**Issue by hermitmaster** [sindrets/diffview.nvim#268]
Title. Started with [e37b2d9](https://github.com/sindrets/diffview.nvim/commit/e37b2d9aaba408954d0e894e27e6f4dbf939ef95). Rolling back one commit restored normal functionality.

**Comment by sindrets** [comment]
Thanks for reporting. It was a bug that caused the layout config not to be respected. Should be fixed now. 

However, I also want to point out that the reason you ended up with horizontal diff splits was because the plugin fell back to respecting your `'diffopt'`. If you always prefer vertical diff splits, I recommend that you add `vertical` to your `diffopt`:

```lua
vim.opt.diffopt:append("vertical")
```

This controls the behavior of i.e. the `:diffsplit` command, and plugins like Fugitive and Diffview respect this option.
