### ISSUE TITLE
Why I don't have color in diffview

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#273]
Help~~

I wonder why I don't have color.

![image](https://user-images.githubusercontent.com/95092244/208622296-91a2c884-6099-4377-a4fb-64c86a9993cd.png)

I use `wezterm`

**Comment by sindrets** [comment]
@LintaoAmons Seems like your color scheme just uses really subtle diff highlighting. You can check your current diff highlights with:

```
hi DiffAdd | hi DiffDelete | hi DiffChange | hi DiffText
```

Then you can adjust it however you want with either `:h :hi` or `:h nvim_set_hl()`.

**Comment by LintaoAmons** [comment]
Can you share the output of your `hi DiffAdd | hi DiffDelete | hi DiffChange | hi DiffText`?
I want use your color settings

**Comment by sindrets** [comment]
You want colors that are appropriate for your color scheme. My diff highlights will be wrong for your color scheme. The way I go about setting up diff highlights is [rather involved](https://github.com/sindrets/dotfiles/blob/7af466e5bc8219385923e75b20b10b8d865cc68c/.config/nvim/lua/user/colorscheme.lua#L148).

But the basic gist is that you want to pick some appropriate colors for additions, deletions and modifications, and then you want to blend those colors with the background color of your current color scheme in order to get the transparent overlay look (as nvim doesn't actually support transparent colors for highlights, so we emulate the look using blending).

So again: these colors are dynamically generated, and thus they're different for each color scheme I use. They most likely won't be right for your color scheme. Regardless, here you go:

```
:hi DiffAdd | hi DiffDelete | hi DiffChange | hi DiffText
DiffAdd        xxx guibg=#313a40
DiffDelete     xxx guibg=#3e2b40
                   links to Comment
DiffChange     xxx guibg=#2e324b
DiffText       xxx guibg=#414868
```

**Comment by LintaoAmons** [comment]
Thanks for your throughly explaination
