### ISSUE TITLE
File entry error on opening diff view

### ISSUE THREAD

**Issue by akinsho** [sindrets/diffview.nvim#28]
Hi 👋🏾 ,

I've recently noticed some errors whilst opening `diffview` with no arguments via `DiffViewOpen` in a couple of different projects. The error that occurs is
```
E5108: Error executing lua ...ack/packer/opt/diffview.nvim/lua/diffview/file-entry.lua:133: Vim(lua):E5108: Error executing lua Vim:E5300: Expected a Number or a String
```
It seems to then prevent the diff for that file from showing correctly. Not a 100% sure what's going on but for a bit more context on my setup.

I lazy load diffview using packer not sure if this relevant using
```lua
use {"sindrets/diffview.nvim", module = "diffview", cmd = "DiffviewOpen"}
```
This all seems to have begun shortly after the api PR was merged if that helps which is when I think maybe the file entry structure was added?

**Comment by sindrets** [comment]
The file entry structure existed before the API, but some things were changed during that time.

The error seems to occur because the `winnr` is somehow invalid, which seems strange because I validate and restore the window layout if it's broken before loading buffers. What is even stranger is that the error indicates that the `winnr` is neither a number nor a string, but it's still able to be concatenated with the lua string in this line:

https://github.com/sindrets/diffview.nvim/blob/0589dc12ff311bbd832316fd596db28196a9ffe0/lua/diffview/file-entry.lua#L133

This is very difficult to fix without a reproducible scenario, it would be very helpful if you could provide a tarball of a git repo and a commit SHA where this happens.

Otherwise could you at least show the output after you get the error, having applied this patch:

```diff
diff --git a/lua/diffview/file-entry.lua b/lua/diffview/file-entry.lua
index 67fca87..246b3ae 100644
--- a/lua/diffview/file-entry.lua
+++ b/lua/diffview/file-entry.lua
@@ -130,6 +130,7 @@ function FileEntry:load_buffers(git_root, left_winid, right_winid)
         table.insert(self.created_bufs, bn)
         a.nvim_win_set_buf(split.winid, bn)
         split.bufid = bn
+        print(vim.inspect(winnr), split.winid, a.nvim_win_is_valid(split.winid), vim.inspect(a.nvim_tabpage_list_wins(0)))
         vim.cmd(winnr .. "windo filetype detect")
       end

```

This might at least help figure out what's going on with the `winnr`.

**Comment by akinsho** [comment]
@sindrets will try and get the output for you 👍🏾 it could very well be something strange on my system or config since it seemed to happen regardless of the repository. But I'll dig in and feedback.

**Comment by akinsho** [comment]
Not sure if this was spurious or due to some config changes I made on my system or what but I haven't been able to reproduce this so I'm going to close this for now as a fluke. If it recurs I'll post back here but it hasn't so far (I mess around with my config a lot so could very easily have been something I did)
