### ISSUE TITLE
How to open a new tab without current buffer?

### ISSUE THREAD

**Issue by LimbicSys** [sindrets/diffview.nvim#30]
When I use `:Diffviewopen`, current buffer is in the new tab. How to disable it?

**Comment by sindrets** [comment]
What do you mean by "current buffer is in the new tab"? Do you just mean that it is listed in the new tab? Because if so, there's nothing you can do about it. Vim Always lists all buffers in all tabs.

Or do you mean that the buffer is open in a window in the diffview, that is not one of the 2 diff splits? Because if so that's not supposed to happen. But I have also never seen that before, so I'm going to need more information on how to reproduce this in that case.

**Comment by LimbicSys** [comment]
I mean the second situation.  It works as expected when I disable nvim-tree.

**Comment by sindrets** [comment]
Ah, then I recon it's related to this: https://github.com/kyazdani42/nvim-tree.lua/pull/421

We had some odd behavior introduced in nvim-tree a few days ago. Please update nvim-tree and see if that solves it.

**Comment by LimbicSys** [comment]
Thanks. It works.
