### ISSUE TITLE
Partially staging files

### ISSUE THREAD

**Issue by david-perez** [sindrets/diffview.nvim#31]
Thank you very much for developing this plugin, it's very useful.

Would it be possible to add support to stage hunks?

In Fugitive's `:Gdiff` view one can run `:diffput` on a visual selection to partially stage a hunk.

**Comment by sindrets** [comment]
I'm glad to hear you find the plugin useful!

Hunk staging is not something I want to implement. There are multiple reasons for this. It has already been implemented well in several other plugins. I would look into [gitgutter](https://github.com/airblade/vim-gitgutter) or the newer [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim). Both of these plugins let you stage hunks directly from the buffer.

There's already a significant overlap of functionality between many of the popular git plugins. I want diffview to be focused on just being a good git diff viewer. I also personally believe that the plugin ecosystem benefits from having more specialized plugins that aim to be good at a small feature set, rather than trying to do everything.

Further, in terms of implementation, there is just no reason to implement it here at the moment. Such an implementation would share practically no code with the current code base, it might as well be a completely separate plugin.

**Comment by david-perez** [comment]
I agree with your thoughts on specialization.

I've used both gitgutter and Fugitive in my workflow since forever.

I know next to nothing about (neo) vim plugin development, and found your suggestion to use gitgutter and the implementation comment odd, thinking how could a separate plugin work together with this diffview if there isn't some kind of explicit integration.

To my surprise, I tried to partially (un)stage hunks using gitgutter's key bindings inside the diffview, and they work! They don't work inside Fugitive's `:Gdiff`. I'm switching to this plugin from `:Gdiff`. This is what I've been wanting for so long.

**Comment by sindrets** [comment]
> and found your suggestion to use gitgutter and the implementation comment odd

Okay, so to elaborate: I am currently not maintaining any data structure of diff hunks in this plugin, because there is no need to. However, plugins like gitgutter and gitsigns.nvim both do. Staging hunks involves generating and applying git patches. This is functionality that both of these plugins have implemented. And like you have discovered, both of these plugins work perfectly fine also from within diffview, so I feel no need to reinvent the wheel.

> how could a separate plugin work together with this diffview if there isn't some kind of explicit integration.

Diffview actually does provide a plugin API though, so if someone really wants to implement hunk staging exactly like how Fugitive does it, it would be possible to do in a separate plugin :)

> I'm switching to this plugin from :Gdiff. This is what I've been wanting for so long.

I'm flattered! Glad you like it :)

**Comment by tuxflo** [comment]
Sorry to comment to an old, already closed issue, but I didn't want to create a new, duplicate one.
I'm also just switching to Diffview because it does exactly what I want. However I also use the already mentioned gitsigns.nvim and commands like `:Gitsigns stage_hunk` are possible from within diffview as well. The only thing that I realized is, that diffview does not automatically update if I changed something like staging or unstaging. I always have to call `DiffViewRefresh` manually after every operation.
Is this just a configuration issue or is diffview not able to update automatically? Or do you know if that's an issue with gitsigns?

**Comment by sindrets** [comment]
> Sorry to comment to an old, already closed issue

@tuxflo No worries!

This requires us to poll the git index to determine when it changes. This is something I might want to implement in the plugin anyway. At least as an option. However, using diffview's hooks (`:h diffview-config-hooks`) and libuv you can actually set this up quite easily in the config:

```lua
require("diffview").setup({
  -- ...
  hooks = {
    view_opened = function(view)
      local DiffView = require("diffview.views.diff.diff_view").DiffView
      if view:instanceof(DiffView) then
        -- Refresh diffview when the git index changes:
        local watcher = vim.loop.new_fs_poll()
        watcher:start(view.git_dir .. "/index", 1000, function(err, prev, cur)
          if not err then
            vim.schedule(function()
              vim.cmd("DiffviewRefresh")
            end)
          end
        end)
      end
    end,
  },
})
```

The number passed to `watcher:start()` is the polling interval in milliseconds. All the libuv stuff is [documented here](https://github.com/luvit/luv/blob/master/docs.md#uvnew_fs_poll).

**Comment by tuxflo** [comment]
Wow, thank a lot for the super fast reply.
Just added the snippet to my config and it works as expected.
Thanks so much!

**Comment by sindrets** [comment]
@tuxflo Just wanted to let you know that as of 7d0d9ecc9ddee85d11a8a52cd30432646cdebf71, this has now been implemented in main, so you no longer need the snippet in your config.

**Comment by e-dong** [comment]
Just adding on that lazygit is another option. This is a neovim wrapper that lets you open lazygit in a floating window: https://github.com/kdheepak/lazygit.nvim
