### ISSUE TITLE
Minor Visual FR: Make the tab title prettier

### ISSUE THREAD

**Issue by chrisgrieser** [sindrets/diffview.nvim#325]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/73286100/227386198-8878d85d-293b-4139-8025-866dc8848fce.png">
(diffview file history is the right one)

It really isn't too pretty, probably since I do not use a bufferline/tabline plugin?

**Comment by sindrets** [comment]
"Tab titles", as in what gets displayed in the `tabline` is controlled by the `:h 'tabline'` option. You can customize this however you want.

The buffers in this plugin are semantically named with a URI structure. The names hold meaningful information about:

- Where the git-dir of the parent git repository is.
- What git revision / index stage number that the object - represented by the buffer - belongs to.
- The path to the object relative to the repository top-level.

I won't set "pretty" buffer names, because buffer names should not be used as decoration. The buffer names are unique identifiers that, in this case, hold meaningful information that can be used in `BufReadCmd` and `BufWriteCmd` events etc.

The buffers created by the plugin are also set as `'nobuflisted'` by default, and as such you shouldn't ever have to see them unless they are displayed in a window. And when they *are* displayed in a window, your `'tabline'` and `'statusline'` options will control how any information about those buffers are displayed in the editor.
