### ISSUE TITLE
Styling on your screenshot

### ISSUE THREAD

**Issue by hrqmonteiro** [sindrets/diffview.nvim#35]
![image](https://user-images.githubusercontent.com/17055027/123962189-8e87aa00-d987-11eb-8659-216059fa5bbd.png)

How come yours have this diagonal lines on the diffs, when on my config they are actually dashes?

![diff](https://user-images.githubusercontent.com/17055027/123962305-b24af000-d987-11eb-8412-888e56b83e16.png)

**Comment by alexzanderr** [comment]
for guys who have full lua config you can do this:
```lua
local set = vim.opt -- set options
set.fillchars = set.fillchars + 'diff:╱'
```
and you will have fancy diagonals :) instead of lame dash sign.

**Comment by Shatur** [comment]
@sindrets What font did you use?
I see you get frequently asked questions about your Neovim design :smile:

**Comment by sindrets** [comment]
@Shatur It's Jet Brains Mono Nerd Font. But if the reason you're asking is that the diagonal lines aren't lining up nicely like in the screenshot: that's not due to the font. That's the terminal emulator. Kitty renders its own box-drawing chars such that they always look nice regardless of line height, column width etc. There are some other terminals that do similar things, like i.e. WezTerm.

> I see you are often asked about your Neovim design

Haha, yeah. Most of them are regarding the diagonal fillchar, so I suppose I should put that in the README :)

**Comment by Shatur** [comment]
> But if the reason you're asking is that the diagonal lines aren't lining up nicely like in the screenshot: that's not due to the font. That's the terminal emulator

Yes, this is why I asked, thank you!
