### ISSUE TITLE
Empty view when submodule.recurse = true

### ISSUE THREAD

**Issue by splitDEV** [sindrets/diffview.nvim#38]
Hi,

Thank you for your plugin, I really like it but unfortunately it just displays the right buffer (sometimes both buffers) as empty when opening `:DiffviewOpen`.

I digged a little and found out that in my `~/.gitconfig`

```ini
[submodule]
recurse = true
```

is responsible for this behavior. When setting it to false everything works fine. I would be glad if you could fix it :-)

**OS:** Linux
**Neovim:** 0.5
**diffview.nvim:** latest commit #36 

Best regard Andy

**Comment by sindrets** [comment]
I see. This is happening because I'm [using a strange trick](https://github.com/sindrets/diffview.nvim/blob/1936824f5986c986befad5995e7bf87ba124d109/lua/diffview/git.lua#L248-L264) to determine whether or not files are binaries using only git. For some reason it doesn't work when this git option i enabled. I'm gonna have to investigate a different way to do this.

As a temporary fix: if you set `diff_binaries = true` in the diffview config it works. But it will also show diffs for all binary files. Which can be slow if you have some big binaries you are modifying.

**Comment by splitDEV** [comment]
As I modify almost only source files, this is a viable workaround and should be fine for the time being.

Thx for the quick response :-)

**Comment by sindrets** [comment]
Fixed via dce5bfe35995535ae985b20af793331f27f7c0c6.
