### ISSUE TITLE
[Feature] `disable_diagnostics` for default view 

### ISSUE THREAD

**Issue by gennaro-tedesco** [sindrets/diffview.nvim#503]
According to the documentation the configuration `view.merge_tool` allows to set `disable_diagnostics = true` to avoid being cluttered with diagnostics while analysing differences and conflicts. 

Is such option available for general default view too? I have tried to set it to no avail, I presume it isn't?

If not, do you reckon it could be added to the default views as well (at the moment I have set up a hook to disable diagnostics in diff view and it works just fine)?

**Comment by sindrets** [comment]
Yeah, good idea. I don't remember why I initially decided to only enable this for the merge tool. It was probably because I saw it as a greater necessity in conflict buffers, as they inevitably have broken syntax due to the conflict markers. But there isn't really a reason why this shouldn't be available in other contexts as well.

**Comment by gennaro-tedesco** [comment]
Thank you for looking into this so quickly, I tested the latest commit and it works as intended!
