### ISSUE TITLE
Open currently diffed file in index

### ISSUE THREAD

**Issue by jandamm** [sindrets/diffview.nvim#58]
Thank you for the nice plugin 👍

One thing I'm currently struggling with is the "missing" `Ge[dit]` from fugitive.
When diffing a file I'd love to have a way to open the currently selected file as a normal buffer.

Main use case is when checking changes of a commit and noticing an error, fix it and return to diffview.

**Comment by sindrets** [comment]
I agree. I've been wanting this feature myself. I'm currently in the process of merging [a big refactor PR](https://github.com/sindrets/diffview.nvim/pull/59). After that's been merged, I'll try resolve most of the pending feature requests, including this one.

**Comment by sindrets** [comment]
@jandamm Does #67 solve your issue?

**Comment by jandamm** [comment]
Yes, this is the feature I was looking for.

I'm just not sure if this mapping is the best way since it prevents to jump to the file under the cursor.
I don't use this feature that often but it might break things for other users.

Also I'd prefer to have use `:split` in the Diffview (which is what `<C-w>f` currently does). From what I've observed this doesn't break the Diffview.
This would allow quick changes like `<C-w><C-f>` change something `ZZ` all while keeping the Diffview open.

**Comment by sindrets** [comment]
> I don't use this feature that often but it might break things for other users.

I'm not too afraid of this, as all the mappings are configurable, and you can simply remove it or change it. I try to avoid using default mappings of course, but in this case: the normal `gf` mappings will soft break the Diffview if they replace one of the diff buffers. Which is why I felt it was convenient to provide this similar functionality to a already familiar mapping. I might change the mapping to just `gf`, as the normal `gf` will always soft break the Diffview.

> Also I'd prefer to have use `:split` in the Diffview (which is what `<C-w>f` currently does). From what I've observed this doesn't break the Diffview.

Then why don't you just do either: 
- `:sp % | setl nodiff` from the right split (the `%` is necessary here. Otherwise the new window inherits `cursorbind` and `scrollbind`)
- Perform the edit directly in the right buffer. When you are comparing local changes against any git rev, the right split will always be the actual local file. You can perform edits and `:w` directly inside Diffview, and it updates on `BufWritePost` as well.

> This would allow quick changes like <C-w><C-f> change something ZZ all while keeping the Diffview open.

What exactly do you mean "while keeping the Diffview open"? It doesn't go away when you leave the tabpage. You can always return to it with i.e. `:h g<Tab>`. If all you want is a mapping to create a split and disable diff mode, you can easily add this mapping to your configuration:

```lua
key_bindings = {
  view = {
    -- other mappings ...
    ["<leader>s"] = "<Cmd>sp % <bar> setl nodiff<CR>"
  }
}
```

**Comment by jandamm** [comment]
`:sp % | setl nodiff` only works when using `:DiffviewOpen`. Then I'd just edit the right buffer directly.

My main issue is using `:DiffviewOpen head..head~` (or any other range). Then the right buffer is not mutable. Using `:sp % | setl nodiff` doesn't open the file but opens the corresponding file in `.git` which isn't mutable either.

Using the new `<C-w><C-f>` does what I'd like as it opens the diffed file in the working copy which is mutable. But it opens it in another tabpage.
I'd love to have a option to open it in a split of the current buffer instead:

```
_________________________
|       |     |   New   |
| Files | Old |---------|
|       |     | Mutable |
_________________________
```

The I can see the `Old` state, the `New` state and modify the current state.

**Comment by sindrets** [comment]
Thank you for the clear explanation. I solved this by implementing all variants of the goto-file mappings. Just let me know if there are any problems with this solution.

```vimhelp
                                                *diffview-nvim-maps-goto_file*
gf                      Open the local version of the file in a new split in a
                        different tabpage. This will target your previous
                        (last accessed) tabpage first. If you have no
                        non-diffview tabpages open, the file will open in a
                        new tabpage. See |diffview-nvim-file-inference| for
                        details on how the file target is determined.

                                          *diffview-nvim-maps-goto_file_split*
<C-w><C-f>              Open the local version of the file in a new split. See
                        |diffview-nvim-file-inference| for details on how the
                        file target is determined.

                                            *diffview-nvim-maps-goto_file_tab*
<C-w>gf                 Open the local version of the file in a new tabpage.
                        See |diffview-nvim-file-inference| for details on how
                        the file target is determined.
```

**Comment by jandamm** [comment]
Thank you for implementing 😊
