### ISSUE TITLE
feat: file tree UI in file panel?

### ISSUE THREAD

**Issue by farbodsz** [sindrets/diffview.nvim#61]
Thanks so much for writing this plugin!

I was wondering what you think of showing the file panel as a file tree, which I think would give you a better idea of which files have changed and how the overall project structure has changed in a diff.

Something like:

```
/path/to/project/

Changes:
M  backend/
M    file_1.py
A    file_2.py
D    file_3.py
M  frontend/
A    components/
A      file_4.tsx
A      file_5.tsx
D    common/
D      file_6.tsx

Showing changes for:
abcdef..bcdefg
```

(obviously with the nice colors that already exist)

This also avoids the problem of having a really long line width since we currently have the file name, the additions/deletions, _and_ the file path:

```
M  example_file.hs 5, 14 src/MyApp/components/internal/
```

**Comment by sindrets** [comment]
[The first time this was brought up](https://github.com/sindrets/diffview.nvim/issues/48) I immediately shut it down as I didn't like the idea. I've since thought about it some more, and I'm no longer directly opposed to the idea. After the recent refactor I did I think it's also a lot more feasible to implement. However, I don't care much for it myself (for the reasons explained in #48), so I won't prioritize it.

But if anyone wants to have a go at it: feel free! It would have to be configurable, and not on by default. The file panel rendering is done [here](https://github.com/sindrets/diffview.nvim/blob/e0ffb1cb7c5ea9e693e5ee5ee3ce1e5f78916ed6/lua/diffview/views/diff/file_panel.lua#L254).

> This also avoids the problem of having a really long line width since we currently have the file name, the additions/deletions, and the file path:

I have intentionally structured these entries with data in order of importance *explicitly* because I know that part of the line will be cut off. In short, I don't think you need to see the whole line most of the time. The entries are sorted by path, and thus files in the same directory *are* grouped together. If you need to see the full path you can just move the file panel to the bottom of the screen.
