### ISSUE TITLE
Tokyonight sidebar color for DiffviewFiles not taking effect

### ISSUE THREAD

**Issue by ourigen** [sindrets/diffview.nvim#82]
Since the newest update that provides tree view, my tokyonight.nvim sidebar color override is not taking effect. Here is my tokyonight.nvim config. 
```
vim.g.tokyonight_sidebars = {
  "terminal",
  "packer",
  "qf",
  "NeogitStatus",
  "DiffviewFiles",
}
vim.cmd[[colorscheme tokyonight]]
```

diffview.nvim config is the default.

Note the diffview.nvim sidebar is a lighter color rather than the darker color in my screenshot below

![](https://user-images.githubusercontent.com/79729735/134814340-b5dbcbc6-7878-4945-a7c8-4ae463e6693a.png)

Sidebar color override is working for all other filetypes, so I don't think it is an issue with tokyonight.nvim

**Comment by sindrets** [comment]
This has nothing to do with any recent update though, as far as I'm aware. I believe this has never worked. I might be wrong though. Do you have a commit where it works?

Regardless, this is not a fault of Diffview, but rather the way that tokyonight tries to apply these highlights. Tokyonight attempts to apply these window highlights on the `FileType` event. This is not enough, because filetypes can be set on buffers while they are still hidden (while they're not open in any window). And because `winhl` is a window local option, nothing happens in this case. Tokyonight should additionally apply these highlights on the `BufWinEnter` event, which happens after a buffer is displayed in a window.

**Comment by ourigen** [comment]
I can't remember a commit but I also haven't opened diffview for a while until recently trying to add it to my workflow again. Perhaps I'm misremembering. The thing I know that's different is the tree view, which I knew was introduced recently so I attributed it to that. Is this issue better addressed to tokyonight.nvim instead?

**Comment by sindrets** [comment]
> I can't remember a commit but I also haven't opened diffview for a while until recently trying to add it to my workflow again. Perhaps I'm misremembering.

@ourigen Typically you would use `git bisect` to find the "bad" commit in this case. But like I said: I believe this has never worked, so you probably don't need to.

> Is this issue better addressed to tokyonight.nvim instead?

Yes. Like I explained, it's the way they are applying the window highlights that doesn't take into consideration whether the buffer is actually displayed in a window.

**Comment by ourigen** [comment]
Gotcha, I will close this issue
