### ISSUE TITLE
diffview opens back up after being closed

### ISSUE THREAD

**Issue by marcusbuffett** [sindrets/diffview.nvim#90]
If I do the following:
1. :DiffviewOpen
2. Close the diff view, but not via :DiffviewClose. :q in my case
3. Save any file

The diff view opens back up. This will keep happening as I save files, until I :DiffviewClose. I'm using Lunarvim on OS X, if that matters. My config is pretty plain, just requiring the package via packer like so:
```
{
  "sindrets/diffview.nvim",
  event = "BufRead",
}
```

**Comment by sindrets** [comment]
This is an upstream issue. Seems like Neovim doesn't send a `TabClosed` event when you close the last window in a tab with `:q`. However vim does this. I'll open an upstream issue soon.

Until that is fixed you should use either `:tabc` or `:DiffviewClose` as described per the documentation. Both of which work almost exactly the same (except `:DiffviewClose` won't close your current tab unless it's a diffview).

**Comment by marcusbuffett** [comment]
Ah gotcha, makes sense. I’m using DiffviewClose for now

**Comment by sindrets** [comment]
@marcusbuffett Actually, upon further investigation I can't reproduce this. I made an assumption on what the issue was, but now I have tested with both Neovim nightly, and 0.5.1 and they both trigger the event correctly on `:q` and the diffview is properly disposed. So unless you can reproduce this with a minimal config I highly suspect this is related to your config.

Here's a template for a minimal config:

<details>
<summary>Click to expand</summary>

```lua
-- mini.lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'sindrets/diffview.nvim',
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  vim.cmd("au TabClosed * echom 'Tab was closed: ' .. expand('<afile>')")
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing dependencies...")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

Make any adjustments necessary to reproduce the issue, then run neovim with:

 `nvim --clean -u path/to/mini.lua`
</details>

**Comment by marcusbuffett** [comment]
Hm actually I can't reproduce this anymore 🤷 same config as before, not sure what changed

**Comment by sindrets** [comment]
Alright, if you find out something else just let me know.

**Comment by jgarciaokode** [comment]
I am able to reproduce this problem, i am closing windows with :q! and after i move to another buffer and save the file then diff is opened again, anyway im going to use the command you provided

**Comment by sindrets** [comment]
@jgarciaokode I assume you're closing every window _except_ for the last one in the tabpage before you're changing the buffer. This will not work because the plugin tracks tabpage IDs and window IDs of diff views. So by not closing the last window you're still using a window in a tabpage that the plugin sees as belonging to a diff view. When you save a file in this window you will trigger the layout function, which recognizes that the view has been partly broken and thus restores the layout.

Again, the only way to properly dispose of a diff view is to either:
- Use `:tabc`
- Use `:DiffviewClose`
- Close **all** windows in the tabpage.

This is documented under `:h diffview-usage`.

**Comment by jgarciaokode** [comment]
@sindrets yeah i imagined it was related to that, many thanks for the quick response and detailed explanation anyway ^^
