### ISSUE TITLE
Error when trying :DiffviewOpen

### ISSUE THREAD

**Issue by vzytoi** [sindrets/diffview.nvim#94]
Hey, I just installed this plugin (nice plugin btw) I when I tried to run `:DiffviewOpen` I got this error :

```
E5108: Error executing lua ...ck\packer\start\diffview.nvim\lua\diffview/git/utils.lua:42: attempt to index local 'name' (a nil value)
```

`:version`:
```
NVIM v0.6.0-dev+205-g9695691ee
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilé par runneradmin@fv-az152-120

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

Configuration:
```lua
use {
        'sindrets/diffview.nvim',
        requires = 'nvim-lua/plenary.nvim'
    }
```
I'm on Windows 10, have a nice day! (:

**Comment by sindrets** [comment]
I have honestly never even tested the plugin on windows before now. But it seems to work almost fine aside from some non-breaking problems regarding path separators. 

The issue seems to be that something is going wrong during parsing of git's output. This could maybe be related to your git config, or there's something wrong in my parser. It would help if you could share the output of `git diff --name-status` from the repo you were having problems with. You can censor the paths if that is sensitive information, but please don't change the formatting in any other way.

Also, have you tried with different repos? If the problem only occurs in one / some of your repos it's probably some git output I've not accounted for in my parser, but if the problem happens with all repos it's more likely to be related to your config.

**Comment by vzytoi** [comment]
Thanks for your answer, the `git diff --name-status` seems to work just fine : 
```
M       init.lua
M       lua/plugins.lua
```
Have a good day (:

**Comment by sindrets** [comment]
@vzytoi I can't reproduce this. You're probably gonna have to do some debugging on your own. I can only make guesses as to what might be causing the problem here:

- Outdated Git.
- Your `:h 'shell'` configuration in nvim and the configuration for your shell. I'm in the process of refactoring to use jobs, but currently this plugin relies on the `:h system()` functions (which will use your configured shell).

I'm sorry that I can't help you directly as I'm unable to reproduce this from my testing on Windows, but I can give you some pointers as to what you need to investigate.

- Check that the `system()` functions work for you in vim. Try calling `:echo system('git diff --name-status')` and check the output.
- In the code:
  - You can use `vim.inspect()` to inspect tables. I would start [looking here](https://github.com/sindrets/diffview.nvim/blob/a38306ddf893b95b55c6cd881605b3232c658e42/lua/diffview/git/utils.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L29), as this is where your error was coming from:
  
```patch
diff --git a/lua/diffview/git/utils.lua b/lua/diffview/git/utils.lua
index ee9d441..e4bd34b 100644
--- a/lua/diffview/git/utils.lua
+++ b/lua/diffview/git/utils.lua
@@ -33,6 +33,9 @@ local function tracked_files(git_root, left, right, args, kind)
   cmd = "git -C " .. vim.fn.shellescape(git_root) .. " diff --numstat " .. args
   local stat_data = vim.fn.systemlist(cmd)
 
+  print("name-status:", vim.inspect(names))
+  print("numstat:", vim.inspect(stat_data))
+
   if not utils.shell_error() then
     for i, s in ipairs(names) do
       local status = s:sub(1, 1):gsub("%s", " ")
```

Let me know if you figure something out, or need more pointers for as to where / what / how to debug further.

**Comment by vzytoi** [comment]
@sindrets Ok so that was just the outdated git ... I just ran `choco update git` and it suddenly worked. My so sorry for losing you time and ty for this amazing plugin!
